version: '3'
services:
  mysql:
    image: mysql:8.0.28
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - default
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./myapp2/sql/myconf:/etc/mysql/conf.d
    command: 
      --default-authentication-plugin=mysql_native_password

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - mysql   
    networks:
      - default 
    volumes:
    - .:/myapp2
    - /myapp2/log
    - /myapp2/tmp
    ports:
      - '3000:3000'
    tty: true
    stdin_open: true

volumes:
  mysql_data:
