version: '3'
services:
  mysql:
    image: mysql:8.0.28
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - default
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql    
    command: 
      --default-authentication-plugin=mysql_native_password

  test-mysql:
    image: mysql:8.0.28
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - default
    ports:
      - "3308:3306"
    command: 
      --default-authentication-plugin=mysql_native_password


  web:
    build:
      context: .
      dockerfile: Dockerfile.ci
    depends_on:
      - mysql
    ports:
      - '3000:3000'
    networks:
      - default
    volumes:
      - .:/myapp2
      - /myapp2/log
      - /myapp2/tmp
    entrypoint: ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]

volumes:
  mysql_data:
