# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: myapp2-mysql-1
  port: 3306

development:
  <<: *default
  database: myapp2_development

test:
  <<: *default
  database: myapp2_development

production:
  <<: *default
  database: myapp2_development
